import type { ContractData, SignerAcknowledgments } from "./contract-types";

export const requiredAcknowledgmentLabels: { key: keyof SignerAcknowledgments; label: string }[] = [
  { key: "completeAgreement", label: "I have received access to the complete Agreement." },
  { key: "reviewedAllPages", label: "I have reviewed page one, page two, and all attached exhibits." },
  { key: "understands", label: "I have read and understand the Agreement." },
  { key: "sufficientTime", label: "I have had sufficient time to review the Agreement." },
  { key: "legalAdviceOpportunity", label: "I have been given an opportunity to seek independent legal advice." },
  { key: "voluntary", label: "I am signing knowingly and voluntarily." },
  { key: "noDuress", label: "I am not signing under duress, coercion, intimidation, manipulation, undue influence, threat, deception, or improper pressure." },
  { key: "noImpairment", label: "I am not impaired by alcohol, illegal drugs, medication, intoxicants, or another condition that prevents me from understanding the Agreement." },
  { key: "bindingEffect", label: "I understand that this Agreement is intended to create legally binding obligations." },
  { key: "evidenceUse", label: "I understand that this Agreement and its signature records may be used as evidence in a court of law or other legal proceeding." },
  { key: "electronicConsent", label: "I consent to use an electronic or digital signature when signing electronically." },
  { key: "equivalentEffect", label: "I intend my electronic or digital signature to have the same legal effect as my handwritten signature, to the fullest extent permitted by law." },
  { key: "accurateInformation", label: "I certify that the information I provided is accurate." },
  { key: "authority", label: "I certify that I have authority to sign for the identified party or organization." },
];

export const emptyAcknowledgments = (): SignerAcknowledgments => ({
  completeAgreement: false,
  reviewedAllPages: false,
  understands: false,
  sufficientTime: false,
  legalAdviceOpportunity: false,
  voluntary: false,
  noDuress: false,
  noImpairment: false,
  bindingEffect: false,
  evidenceUse: false,
  electronicConsent: false,
  equivalentEffect: false,
  accurateInformation: false,
  authority: false,
});

const today = "2026-07-17";

export const sampleContract: ContractData = {
  metadata: {
    agreementType: "Church facility rental agreement",
    customTitle: "",
    contractNumber: "CFRA-2026-0717",
    effectiveDate: "2026-07-20",
    creationDate: today,
    lastModified: today,
    status: "Draft",
    attorneyNoticeAccepted: false,
    includeDisclaimerInContract: false,
    locked: false,
  },
  property: {
    name: "Heritage Community Center",
    propertyType: "Church and community facility",
    address: { street: "1840 Providence Road", city: "Charlotte", state: "NC", zip: "28211", county: "Mecklenburg" },
    parcelOrUnit: "",
    building: "Main Building",
    floor: "Ground Floor",
    suite: "",
    rentedAreas: ["Sanctuary", "Fellowship hall", "Classroom"],
    customArea: "Classrooms 101–103",
    entryDoors: "East fellowship-hall entrance and main sanctuary entrance",
    areasIncluded: "Sanctuary, fellowship hall, classrooms 101–103, and designated restrooms",
    areasExcluded: "Administrative offices, pastoral suite, nursery storage, and west maintenance rooms",
    amenities: ["Restrooms", "Furniture", "Kitchen access", "Sound system", "Audio-visual equipment", "Wi-Fi"],
    accessInstructions: "The designated representative may enter through the east entrance no earlier than the approved setup time.",
    keyInstructions: "One access credential will be issued. Codes may not be shared and must be returned or disabled at termination.",
    permittedUse: "Weekly worship services, Bible study, volunteer meetings, and related ministry activities",
    prohibitedUses: "Commercial sales, overnight stays, political campaigning, or any unlawful activity",
    limitations: "Kitchen use is limited to warming and serving prepared food unless separately approved in writing.",
  },
  lessor: {
    legalName: "Heritage Community Property Association, Inc.",
    organizationName: "Heritage Community Property Association",
    entityType: "North Carolina nonprofit corporation",
    address: { street: "1840 Providence Road", city: "Charlotte", state: "NC", zip: "28211", county: "Mecklenburg" },
    phone: "(704) 555-0142",
    email: "facilities@heritageexample.org",
    website: "https://heritageexample.org",
    responsible: { fullName: "Marian Ellis", title: "Facilities Director", phone: "(704) 555-0148", email: "marian.ellis@heritageexample.org", emergencyContact: "Jordan Bell, (704) 555-0109", hasAuthority: true, signingCapacity: "organizational" },
    incorporated: true,
    incorporationState: "North Carolina",
    nonprofit: true,
  },
  renter: {
    legalName: "New Day Fellowship Church, Inc.",
    organizationName: "New Day Fellowship Church",
    entityType: "North Carolina nonprofit religious corporation",
    address: { street: "722 Briar Creek Road", city: "Charlotte", state: "NC", zip: "28205", county: "Mecklenburg" },
    phone: "(704) 555-0185",
    email: "office@newdayexample.org",
    website: "https://newdayexample.org",
    responsible: { fullName: "Rev. Andre Coleman", title: "Senior Pastor", phone: "(704) 555-0187", email: "andre.coleman@newdayexample.org", emergencyContact: "Dana Cole, (704) 555-0191", hasAuthority: true, signingCapacity: "organizational" },
    incorporated: true,
    incorporationState: "North Carolina",
    nonprofit: true,
    purpose: "Recurring Sunday worship services and Wednesday evening ministry programs",
    personalFinancialResponsibility: false,
  },
  term: {
    rentalPattern: "recurring-weekly",
    startDate: "2026-08-02",
    endDate: "2027-07-31",
    initialAccessDate: "2026-08-02",
    initialAccessTime: "07:30",
    threeMonthCommitmentEnabled: true,
    noticePeriodDays: 15,
    specialEventDates: ["2026-12-20"],
    unavailableDates: ["2026-12-27"],
    termType: "month-to-month",
    renewalPeriod: "One month",
    renewalDate: "2027-08-01",
    renewalNoticeDays: 15,
    renewalInWriting: true,
    holdoverTerms: "Continues month-to-month at the then-current rate after the fixed term unless either party gives required written notice.",
    finalVacateDate: "2027-07-31",
    finalKeyReturnDate: "2027-08-01",
  },
  schedule: [
    { id: "schedule-wed", day: "Wednesday", recurrence: "Every week", setupStart: "17:30", rentalStart: "18:00", rentalEnd: "21:00", cleanupEnd: "21:30", firstOccurrence: "2026-08-05", lastOccurrence: "2027-07-28", expectedAttendees: 85, area: "Fellowship hall and classrooms 101–103", additionalCharge: 0, notes: "Bible study and youth ministry" },
    { id: "schedule-sun", day: "Sunday", recurrence: "Every week", setupStart: "07:30", rentalStart: "08:00", rentalEnd: "14:00", cleanupEnd: "14:30", firstOccurrence: "2026-08-02", lastOccurrence: "2027-07-25", expectedAttendees: 210, area: "Sanctuary and fellowship hall", additionalCharge: 0, notes: "Worship service and fellowship" },
  ],
  payment: {
    calculationMethod: "month",
    rentalPrice: 3200,
    hourlyRate: 0,
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 3200,
    flatAmount: 0,
    pricePerOccurrence: 0,
    frequency: "Monthly",
    dueDay: "1st day of each month",
    firstPaymentDate: "2026-08-01",
    finalPaymentDate: "2027-07-01",
    proratedFirst: 0,
    proratedFinal: 0,
    gracePeriodDays: 5,
    lateFee: 125,
    returnedPaymentFee: 45,
    electronicPaymentFee: 0,
    overtimeRate: 150,
    additionalHourRate: 125,
    recurringFees: [{ label: "Storage room", amount: 150 }],
    oneTimeFees: [{ label: "Access credential setup", amount: 35 }],
    taxes: 0,
    acceptedMethods: ["ACH", "Check"],
    payeeName: "Heritage Community Property Association, Inc.",
    paymentAddress: "1840 Providence Road, Charlotte, NC 28211",
    electronicInstructions: "ACH instructions will be delivered through the secure payment portal.",
    utilitiesIncluded: true,
    wifiIncluded: true,
    cleaningIncluded: false,
    additionalPaymentNotes: "",
  },
  securityDeposit: {
    amount: 3200,
    dueDate: "2026-07-27",
    paymentMethod: "ACH",
    status: "Due",
    datePaid: "",
    receiptNumber: "",
    receivedBy: "",
    recordReference: "",
    deductionConditions: ["Property damage", "Unpaid rent", "Unpaid fees", "Excessive cleaning", "Missing equipment", "Missing furniture", "Missing keys", "Unauthorized use", "Overtime charges", "Other documented losses"],
    otherLosses: "Other documented losses permitted by the Agreement and applicable law",
    refundAddress: "722 Briar Creek Road, Charlotte, NC 28205",
    refundMethod: "ACH or check",
    inspectionDays: 7,
  },
  cancellation: {
    policyType: "custom",
    refundUntil: "",
    partialRefundPercent: 50,
    reservationPayment: 0,
    customPolicy: "After the initial commitment, either party may end the agreement with the written notice selected in the rental term.",
  },
  notices: {
    lessorAddress: "Heritage Community Property Association, Attn: Facilities Director, 1840 Providence Road, Charlotte, NC 28211",
    renterAddress: "New Day Fellowship Church, Attn: Senior Pastor, 722 Briar Creek Road, Charlotte, NC 28205",
    lessorEmail: "facilities@heritageexample.org",
    renterEmail: "office@newdayexample.org",
    emailPermitted: true,
    certifiedMailRequired: false,
    handDeliveryPermitted: true,
    overnightPermitted: true,
    textPermitted: false,
    designatedRecipient: "The responsible representatives identified on page one",
    mailedReceivedRule: "Three business days after deposit in U.S. mail, unless actual receipt occurs earlier",
    emailedReceivedRule: "When sent without a delivery-failure notice during business hours; otherwise, the next business day",
    businessHours: "Monday–Friday, 9:00 AM–5:00 PM Eastern Time, excluding legal holidays",
  },
  propertyRules: ["No smoking or vaping", "No alcohol or illegal drugs", "No unlawful activity or gambling", "No weapons except as permitted by law and property policy", "No subleasing or assignment without written approval", "No overnight stays or permanent residency", "No candles or open flames", "Children must be properly supervised", "Use only approved areas and schedule", "Secure doors and windows", "Turn off lights and equipment", "Leave property clean and remove trash", "Return furniture to its original location", "Report damage immediately", "Do not duplicate keys or share codes", "Follow fire code, safety requirements, laws, and property policies", "Food only in approved areas"],
  customRules: ["Sunday sound checks must conclude before 8:00 AM."],
  insurance: {
    required: true,
    policyLimit: 1000000,
    certificateRequired: true,
    additionalInsured: true,
    deadline: "2026-07-27",
    responsibilities: ["Guests", "Employees", "Volunteers", "Contractors", "Vendors", "Children"],
    incidentReportRequired: true,
    indemnificationSelected: false,
    indemnificationText: "",
    holdHarmlessSelected: false,
    waiverSelected: false,
    limitationSelected: false,
  },
  defaults: {
    selectedDefaults: ["Failure to pay rent", "Repeated late payment", "Unauthorized use", "Use outside approved hours", "Property damage", "Violation of property rules", "Loss of required insurance", "Illegal activity", "Material misrepresentation", "Unauthorized assignment or subleasing"],
    curePeriodDays: 5,
    writtenNoticeRequired: true,
    immediateTerminationReasons: ["Illegal activity", "Credible threat to safety", "Intentional material property damage"],
    emergencyCancellation: true,
    reschedulingAllowed: true,
    refundProcedure: "Any approved refund will be issued within 15 business days using the original payment method when practical.",
    forceMajeure: true,
  },
  customClauses: [],
  governingLaw: { state: "North Carolina", county: "Mecklenburg", venue: "State courts located in Mecklenburg County, North Carolina", mediation: true, arbitration: false, attorneyFees: false, juryTrialWaiver: false, noticeBeforeActionDays: 15 },
  exhibits: [
    { id: "exhibit-a", label: "Exhibit A", title: "Rental Schedule", fileName: "", included: true },
    { id: "exhibit-b", label: "Exhibit B", title: "Property Rules and Cleaning Checklist", fileName: "", included: true },
    { id: "exhibit-c", label: "Exhibit C", title: "Equipment and Furniture Inventory", fileName: "", included: true },
    { id: "exhibit-d", label: "Exhibit D", title: "Certificate of Insurance", fileName: "", included: true },
  ],
  signatureMethod: "hybrid",
  signatureOptions: { witnessEnabled: false, notaryEnabled: false },
  signatures: {},
  audit: [{ id: "audit-created", at: `${today}T12:00:00.000Z`, action: "Contract created", actor: "Contract Preparer", details: "Sample church facility agreement created from required-clause revision 2026.1.", documentHash: "Pending first save" }],
  versions: [],
  admin: { finalPageAcknowledgment: true, initialsEachLegalPage: false, requiredClauseRevision: "2026.1" },
};

export const createNewContract = (): ContractData => JSON.parse(JSON.stringify(sampleContract));

export const createBlankContract = (): ContractData => {
  const contract = createNewContract();
  const stamp = new Date().toISOString().slice(0, 10).replaceAll("-", "");
  contract.metadata = { ...contract.metadata, agreementType: "Commercial facility rental agreement", contractNumber: `CFRA-${stamp}-001`, effectiveDate: "", creationDate: new Date().toISOString().slice(0, 10), lastModified: new Date().toISOString().slice(0, 10), status: "Draft", attorneyNoticeAccepted: false, includeDisclaimerInContract: false, locked: false };
  contract.property = { ...contract.property, name: "", propertyType: "Commercial facility", address: { street: "", city: "", state: "NC", zip: "", county: "" }, rentedAreas: [], customArea: "", areasIncluded: "", areasExcluded: "", permittedUse: "", prohibitedUses: "", limitations: "" };
  contract.lessor = { ...contract.lessor, legalName: "", organizationName: "", entityType: "Nonprofit corporation", address: { street: "", city: "", state: "NC", zip: "", county: "" }, phone: "", email: "", website: "", responsible: { ...contract.lessor.responsible, fullName: "", title: "", phone: "", email: "", emergencyContact: "", hasAuthority: false } };
  contract.renter = { ...contract.renter, legalName: "", organizationName: "", entityType: "Church", address: { street: "", city: "", state: "NC", zip: "", county: "" }, phone: "", email: "", website: "", responsible: { ...contract.renter.responsible, fullName: "", title: "", phone: "", email: "", emergencyContact: "", hasAuthority: false } };
  contract.renter.purpose = "";
  contract.renter.personalFinancialResponsibility = false;
  contract.term = { ...contract.term, rentalPattern: "one-day", startDate: "", endDate: "", initialAccessDate: "", renewalDate: "", finalVacateDate: "", finalKeyReturnDate: "", threeMonthCommitmentEnabled: false, noticePeriodDays: 15, specialEventDates: [], unavailableDates: [] };
  contract.schedule = [];
  contract.payment = { ...contract.payment, rentalPrice: 0, hourlyRate: 0, dailyRate: 0, weeklyRate: 0, monthlyRate: 0, flatAmount: 0, pricePerOccurrence: 0, firstPaymentDate: "", finalPaymentDate: "", recurringFees: [], oneTimeFees: [] };
  contract.securityDeposit = { ...contract.securityDeposit, amount: 0, dueDate: "", datePaid: "", receiptNumber: "", receivedBy: "", recordReference: "" };
  contract.cancellation = { policyType: "fully-refundable", refundUntil: "", partialRefundPercent: 50, reservationPayment: 0, customPolicy: "" };
  contract.notices = { ...contract.notices, lessorAddress: "", renterAddress: "", lessorEmail: "", renterEmail: "" };
  contract.customClauses = [];
  contract.signatures = {};
  contract.signatureOptions = { witnessEnabled: false, notaryEnabled: false };
  contract.audit = [{ id: crypto.randomUUID(), at: new Date().toISOString(), action: "Contract created", actor: "Contract Preparer", details: "New contract started from the universal commercial-rental template.", documentHash: "Pending first save" }];
  contract.versions = [];
  return contract;
};
